#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate a visual-only T800 URDF for Gazebo hard-sync visualization.

Input:
  urdf/serial_t800.urdf
Output:
  urdf/serial_t800_visual_sync.urdf

What it changes:
  1) Add dummy_root -> LINK_BASE fixed joint to avoid KDL root inertia warning.
  2) Remove all <collision> blocks, because this model is only for visualization.
  3) Add Gazebo tags to disable gravity and self collision on all real links,
     reducing drift/falling when the model is only driven by hard state sync.
  4) Does NOT add ros_control transmission or gazebo_ros_control plugin.
"""

from pathlib import Path
import xml.etree.ElementTree as ET
from xml.dom import minidom

PKG_DIR = Path(__file__).resolve().parent
INPUT_URDF = PKG_DIR / "urdf" / "serial_t800.urdf"
OUTPUT_URDF = PKG_DIR / "urdf" / "serial_t800_visual_sync.urdf"

DUMMY_LINK = "dummy_root"
DUMMY_JOINT = "dummy_root_to_LINK_BASE"
BASE_LINK = "LINK_BASE"


def remove_elements_by_tag(parent: ET.Element, tag: str) -> int:
    removed = 0
    for child in list(parent):
        if child.tag == tag:
            parent.remove(child)
            removed += 1
    return removed


def add_dummy_root(robot: ET.Element) -> None:
    links = {x.attrib.get("name") for x in robot.findall("link")}
    joints = {x.attrib.get("name") for x in robot.findall("joint")}

    if DUMMY_LINK not in links:
        robot.insert(0, ET.Element("link", {"name": DUMMY_LINK}))

    if DUMMY_JOINT not in joints:
        joint = ET.Element("joint", {"name": DUMMY_JOINT, "type": "fixed"})
        ET.SubElement(joint, "origin", {"xyz": "0 0 0", "rpy": "0 0 0"})
        ET.SubElement(joint, "parent", {"link": DUMMY_LINK})
        ET.SubElement(joint, "child", {"link": BASE_LINK})
        robot.insert(1, joint)


def remove_all_collisions(robot: ET.Element) -> int:
    count = 0
    for link in robot.findall("link"):
        count += remove_elements_by_tag(link, "collision")
    return count


def remove_old_generated_gazebo_tags(robot: ET.Element) -> None:
    for elem in list(robot):
        if elem.tag != "gazebo":
            continue
        # Remove tags generated by this script. Keep unrelated gazebo tags if any.
        ref = elem.attrib.get("reference", "")
        marker = elem.find("visual_sync_generated")
        if ref or marker is not None:
            robot.remove(elem)


def add_gazebo_visual_sync_tags(robot: ET.Element) -> int:
    count = 0
    for link in robot.findall("link"):
        name = link.attrib.get("name")
        if not name or name == DUMMY_LINK:
            continue
        gz = ET.Element("gazebo", {"reference": name})
        ET.SubElement(gz, "gravity").text = "false"
        ET.SubElement(gz, "selfCollide").text = "false"
        # Marker, so repeated generation can remove only our own tags.
        ET.SubElement(gz, "visual_sync_generated").text = "true"
        robot.append(gz)
        count += 1
    return count


def get_movable_joints(robot: ET.Element):
    names = []
    for joint in robot.findall("joint"):
        name = joint.attrib.get("name")
        jtype = joint.attrib.get("type")
        if name and jtype not in ("fixed", None):
            names.append(name)
    return names


def pretty_write(root: ET.Element, path: Path) -> None:
    rough = ET.tostring(root, encoding="utf-8")
    pretty = minidom.parseString(rough).toprettyxml(indent="  ")
    pretty = "\n".join(line for line in pretty.splitlines() if line.strip())
    path.write_text(pretty + "\n", encoding="utf-8")


def main() -> None:
    if not INPUT_URDF.exists():
        raise FileNotFoundError(f"Input URDF not found: {INPUT_URDF}")

    tree = ET.parse(INPUT_URDF)
    robot = tree.getroot()
    if robot.tag != "robot":
        raise RuntimeError("Input XML root is not <robot>.")

    add_dummy_root(robot)
    removed_collisions = remove_all_collisions(robot)
    remove_old_generated_gazebo_tags(robot)
    gazebo_tags = add_gazebo_visual_sync_tags(robot)
    movable_joints = get_movable_joints(robot)

    pretty_write(robot, OUTPUT_URDF)

    print(f"Generated: {OUTPUT_URDF}")
    print(f"Removed collision blocks: {removed_collisions}")
    print(f"Added gazebo visual-sync tags: {gazebo_tags}")
    print(f"Movable joints: {len(movable_joints)}")
    for j in movable_joints:
        print(f"  - {j}")


if __name__ == "__main__":
    main()
